In [4]:
import numpy as np

In [2]:
a = [1,2,3]
a.shape

AttributeError: 'list' object has no attribute 'shape'

In [5]:
a= np.array([1,1,0,0,0,1,1,0,0,1,1,1,1,0,0,1,1,1,1,1,0,1,1,1])
a = np.reshape(a,(4,6))
a.shape

(4, 6)

In [6]:
"a" in ("appel")

True

In [17]:
a = np.array([[[1,2],[1,2],[1,2]],[[1,2],[1,2],[1,2],[1,2]]])

In [21]:
a = np.array([[1,2],[1,2]])
b = np.array([[3,2],[1,2]])

In [27]:
a > 1

array([[False,  True],
       [False,  True]])

In [28]:
b > 1

array([[ True,  True],
       [False,  True]])

In [29]:
(a > 1) & (b > 1)

array([[False,  True],
       [False,  True]])

In [14]:
np.count_nonzero(a[0:2][:])

6

In [28]:
for j in a[[0,1],:]:
    print(j)
    print(j.shape)

[1 2 5]
(3,)
[3 4 5]
(3,)


In [7]:
np.gradient(np.array([1]))

ValueError: Shape of array too small to calculate a numerical gradient, at least (edge_order + 1) elements are required.

In [55]:
for i in range(int(b.shape[0]/2)):
    print(i)

0
1


In [63]:
a = np.array([[1,2,3,4],[1,2,3,4]])

In [72]:
a.shape

(2, 4)

In [74]:
np.array([a[i][:2] for i in range(a.shape[0])])

array([[1, 2],
       [1, 2]])

In [65]:
a[:][int(a.shape[0]/2)]

array([1, 2, 3, 4])

In [40]:
b[:(b.shape[1]/2)][:(b.shape[0]/2)]

TypeError: slice indices must be integers or None or have an __index__ method